### ISSUE TITLE
 Error running jOOQ code generation tool: Error while exporting schema: Connection to localhost:49274 refused

### ISSUE THREAD

**Issue by bzlat** [sabomichal/jooq-meta-postgres-flyway#157]
Hi Michal,

First things first, thank you for this project.

I faced a problem while using the `jooq-codegen-maven:3.14.16` plugin together with `jooq-meta-postgres-flyway:1.0.7` on a `macos v13.x` with `Colima` versions `0.4.x` and `0.5.5`, where the code gen tool tries to connect to the `PostgreSQL` container while the container is not ready to accept connections yet:
```
[INFO] Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
[INFO] Checking the system...
[INFO] ✔︎ Docker server version should be at least 1.6.0
[INFO] Creating container for image: postgres:14.5
[INFO] Container postgres:14.5 is starting: 3933afa0422b908ea6e59e41b950a97a00683f31d3457eeb2a0939c9d55c00ac
[INFO] Container postgres:14.5 started in PT1.923275S
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.055 s
[INFO] Finished at: 2023-06-19T22:49:04+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.jooq:jooq-codegen-maven:3.14.16:generate (generate-postgres) on project analytics-connector-opg: Error running jOOQ code generation tool: Error while exporting schema: Connection to localhost:49274 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections. Connection refused
```

I also tried the lastest version of both the `jooq-codegen-maven` plugin and `jooq-meta-postgres-flyway` configuring various `postgres` image versions - from `11.x` to `14.x` and the behaviour remains. The problem first appeared when I switched from using `Docker Desktop` to `Colima`.

After adding an explicit waiting strategy, more specifically the `HostPortWaitingStrategy`, everything returned to normal and I can now reliably run my tests.

I made a small `PR`, in case you find this something worth adding: https://github.com/sabomichal/jooq-meta-postgres-flyway/pull/156

Thank you in advance for your time and consideration

**Comment by sabomichal** [comment]
Thanks, tbh I was not aware this could happen.
