### ISSUE TITLE
Add dockerImage property to Readme

### ISSUE THREAD

**Issue by renedupont** [sabomichal/jooq-meta-postgres-flyway#28]
Hey,
first off, thanks for that little project! 

I just wanted to mention that I had to look into the code to find that there is the very helpful property `dockerImage` which I needed to have the same postgres image as our actual app database.
I think it would be beneficial for other users to learn about this option already in the readme. Your given example in the readme does not include it.

That's all!
Thanks

PS: I'm using it with gradle, if you're interested for a gradle usage example snippet for your readme, let me know.

**Comment by sabomichal** [comment]
Thanks for reporting the issue. If you could provide that example, it would be great! If you could do it by opening the PR, it would be even better.
Thank you.

**Comment by sabomichal** [comment]
Readme file was updated.
